### PR TITLE
AdaptiveImage.jsx prop fix for ImgEl

### PR DESCRIPTION
**Pull request by FabianHoffmannIntive**
Hi,
I've found little bug. Because of that bug the alt prop of image can not be used properly. Please see PR :)

### CODE REVIEW

**Comment by peterlazzarino** [comment]
Good catch 😄  I'll follow up when the new version is released, been a while since I've been in this repo.

**Comment by FabianHoffmannIntive** [comment]
> Good catch 😄 I'll follow up when the new version is released, been a while since I've been in this repo.

Thank you. I will be thankful, cuz we use that library in our app and need alts regarding WCAG and Google Insights : ) When do you plan next release?

**Comment by peterlazzarino** [comment]
Great, I will have it out ASAP, tonight or tomorrow night. Would be interested to hear if you have other recommendations or ideas for this repo. I enjoyed working on it and would be willing to add features if you have thoughts!

**Comment by FabianHoffmannIntive** [comment]
> Great, I will have it out ASAP, tonight or tomorrow night. Would be interested to hear if you have other recommendations or ideas for this repo. I enjoyed working on it and would be willing to add features if you have thoughts!

Sure :) thank you

**Comment by peterlazzarino** [comment]
FYI, I am having some NPM issues Im working through with support, hoping I can get it before the end of the week

**Comment by FabianHoffmannIntive** [comment]
> FYI, I am having some NPM issues Im working through with support, hoping I can get it before the end of the week

Thank you Peter for support. Waiting for release

**Comment by FabianHoffmannIntive** [comment]
> FYI, I am having some NPM issues Im working through with support, hoping I can get it before the end of the week

Hello Peter, any news? :)

**Comment by peterlazzarino** [comment]
@FabianHoffmannIntive please try now, just published 1.9.0

**Comment by peterlazzarino** [comment]
Actually scratch that there was an issue with that build, please use 1.9.1

**Comment by FabianHoffmannIntive** [comment]
> Actually scratch that there was an issue with that build, please use 1.9.1

Gracias Senior! :)

**Pull request merged**
